name: Mac deploy

on: [workflow_dispatch]

env:
  BUILD_TYPE: Release # Change build type here.

jobs:
  build:
  
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 6.2.4 # Update Qt version here.
        aqtversion: '>=0.9.7'

    - name: Build
      shell: bash
      run: |
        brew install boost
        cd build
        cmake ..
        cmake --build . --config $BUILD_TYPE --target Degate

    - name: Prepare binaries
      shell: bash
      run: |
        cd build/out/bin/
        $Qt5_Dir/bin/macdeployqt ./Degate.app
        
    - name: Upload Degate binaries
      uses: actions/upload-artifact@v2
      with:
        name: Degate_binaries_Mac_x64
        path: build/out/bin/
        
    - name: Create Degate installer
      shell: bash
      # Update the Qt Installer Framework (ifw) version here (by providing the exe download link and changing the exe name/path).
      run: |
        brew install wget
        brew install p7zip
        cp -R build/out/bin/ etc/installer/packages/Degate/data
        cd etc/installer
        wget https://download.qt.io/online/qtsdkrepository/mac_x64/desktop/tools_ifw/qt.tools.ifw.44/4.4.1-0-202206210643ifw-mac-x64.7z
        7z x 4.4.1-0-202206210643ifw-mac-x64.7z -y
        ./Tools/QtInstallerFramework/4.4/bin/binarycreator --offline-only -c config/config.xml -p packages "mac_deploy_offline/Degate_offline_installer_Mac_x64"
        ./Tools/QtInstallerFramework/4.4/bin/binarycreator --online-only -c config/config.xml -p packages "mac_deploy_online/Degate_online_installer_Mac_x64"
        
    - name: Upload Degate offline installer
      uses: actions/upload-artifact@v2
      with:
        name: Degate_offline_installer_Mac_x64
        path: etc/installer/mac_deploy_offline/

    - name: Upload Degate online installer
      uses: actions/upload-artifact@v2
      with:
        name: Degate_online_installer_Mac_x64
        path: etc/installer/mac_deploy_online/
        
    - name: Create Degate update
      shell: bash
      run: |
        cd etc/installer
        ./Tools/QtInstallerFramework/4.4/bin/repogen -p packages repository
      
    - name: Upload Degate update
      uses: actions/upload-artifact@v2
      with:
        name: Degate_update_Mac_x64
        path: etc/installer/repository
